version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: continuumio/miniconda3

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/bsipos/bsipos-conda
    resource_class: medium

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
            keys:
            #- v1-dependencies-{{ checksum "conda_base.txt" }}
            # fallback to using the latest cache if no exact match is found
            - cache-v2-

      - run:
          name: install dependencies
          command: |
            conda init -q bash
            source $HOME/.bashrc
            git config --global user.email "sbotond"
            git config --global user.name "Botond Sipos"
            git config --global core.editor ""
            conda config --add channels bioconda
            conda config --add channels conda-forge
            #rm -fr conda_base
            if [ ! -e ./conda_base ];then conda create -p ./conda_base;fi
            conda activate ./conda_base
            conda update -q -y -n base -c defaults conda
            conda install -y -q anaconda anaconda-client conda-build cmake make gcc_linux-64 gxx_linux-64 \
            gfortran_linux-64 openssl conda-verify patchelf \
            python-edlib parasail-python hmmer tqdm matplotlib-base seaborn six pandas
            conda update --all -y -q
            GO_TAR=go1.14.4.linux-amd64.tar.gz
            export GOOS="linux" GOARCH="amd64"
            export GOROOT=`pwd -P`/conda_base/go
            GO_URL="https://dl.google.com/go/$GO_TAR"
            if [ ! -e $GOROOT ]; then wget $GO_URL && tar -xzf $GO_TAR -C conda_base ; rm -f go*.tar.gz* ;fi
            export PATH=`pwd -P`/conda_base/go/bin:$PATH
            export GOPATH=`pwd -P`/conda_base/go.pkgs
            export GOOS="linux" GOARCH="amd64"
            go version
            go get -u  github.com/shenwei356/seqkit/seqkit
            go get -u  github.com/shenwei356/csvtk/csvtk
            conda-build purge
            export PKG_RES="pkg_res"
            rm -fr $PKG_RES
            mkdir -p $PKG_RES/linux-64 $PKG_RES/osx-64
            echo $(echo `date` | openssl dgst -sha256 -)  > conda_base/CACHE_KEY1

      - save_cache:
            paths:
              - ./conda_base
            key: cache-v2-{{ checksum "conda_base/CACHE_KEY1" }}

      - run:
          name: build pychopper_dev (noarch)
          command: |
            source $HOME/.bashrc
            conda activate ./conda_base
            PKG_NAME=pychopper_dev
            BASE=`pwd -P`/pychopper
            export PATH=`pwd -P`/conda_base/go/bin:$PATH
            export GOPATH=`pwd -P`/conda_base/go.pkgs
            export GOROOT=`pwd -P`/conda_base/go
            export GOOS="linux" GOARCH="amd64"
            cd pychopper
            git clone https://github.com/nanoporetech/pychopper.git
            cd pychopper
            git reset --hard origin/dev
            COM=`git rev-parse --short HEAD`
            cd $BASE
            VER=$(grep 'version=' pychopper/setup.py | head -n 1 | cut -d $'=' -f 2 | sed "s/'//g" | sed "s/,//g")
            export BUILD_STRING="${COM}"
            echo "{% set version = \"$VER\" %}" > $BASE/meta.yaml
            cat meta.yaml.in >> meta.yaml
            conda config --set anaconda_upload no
            export PKG_RES="pkg_res"
            conda-build --output-folder $PKG_RES .


      - run:
          name: upload pychopper_dev
          command: |
            source $HOME/.bashrc
            conda activate ./conda_base
            export PKG_RES="pychopper/pkg_res"
            PKGS=`find $PKG_RES -name 'pychopper*bz2'`
            for PKG in $PKGS
            do 
            echo $PKG
            anaconda -t ${ANACONDA_TOKEN} upload --force --register -u bsipos -l main $PKG
            done


      - run:
          name: build seqkit (linux)
          command: |
            source $HOME/.bashrc
            conda activate ./conda_base
            BASE=`pwd -P`/seqkit
            PKG_NAME=seqkit
            export PATH=`pwd -P`/conda_base/go/bin:$PATH
            export GOPATH=`pwd -P`/conda_base/go.pkgs
            export GOROOT=`pwd -P`/conda_base/go
            export GOOS="linux" GOARCH="amd64"
            PKG_NAME=seqkit-bsipos
            cd $GOPATH/src/github.com/shenwei356/seqkit/seqkit
            git remote add bsipos https://github.com/bsipos/seqkit.git
            git fetch --all
            git reset --hard bsipos/master
            COM=`git rev-parse --short HEAD`
            VER=$(grep 'const VERSION' cmd/version.go | sed -r 's/^.*= "(.+)"$/\1/')
            echo $VER
            export BUILD_STRING="${COM}"
            sed "s/const VERSION = .*$/const VERSION = \"${VER}_${BUILD_STRING}\"/" cmd/version.go > version_tmp.go
            mv version_tmp.go cmd/version.go
            go get ./...
            CGO_ENABLED=0 go build -a -tags netgo
            mv seqkit $BASE/
            echo "{% set version = \"$VER\" %}" > $BASE/meta.yaml
            export MY_ARCH="linux_amd64"
            cd $BASE
            cat meta.yaml.in >> meta.yaml
            uname -a
            file seqkit
            export PKG_RES="pkg_res"
            conda-build --output-folder $PKG_RES .

      - run:
          name: build seqkit (MacOS)
          command: |
            source $HOME/.bashrc
            conda activate ./conda_base
            BASE=`pwd -P`/seqkit
            PKG_NAME=seqkit
            export PATH=`pwd -P`/conda_base/go/bin:$PATH
            export GOPATH=`pwd -P`/conda_base/go.pkgs
            export GOROOT=`pwd -P`/conda_base/go
            export GOOS="darwin" GOARCH="amd64"
            PKG_NAME=seqkit-bsipos
            cd $GOPATH/src/github.com/shenwei356/seqkit/seqkit
            #git remote add bsipos https://github.com/bsipos/seqkit.git
            git fetch --all
            git reset --hard bsipos/master
            COM=`git rev-parse --short HEAD`
            VER=$(grep 'const VERSION' cmd/version.go | sed -r 's/^.*= "(.+)"$/\1/')
            echo $VER
            export BUILD_STRING="${COM}"
            sed "s/const VERSION = .*$/const VERSION = \"${VER}_${BUILD_STRING}\"/" cmd/version.go > version_tmp.go
            mv version_tmp.go cmd/version.go
            go get ./...
            CGO_ENABLED=0 go build -a -tags netgo
            mv seqkit $BASE/
            echo "{% set version = \"$VER\" %}" > $BASE/meta.yaml
            export MY_ARCH="osx_amd64"
            cd $BASE
            cat meta.yaml.in >> meta.yaml
            uname -a
            file seqkit
            mkdir -p pkg_tmp/linux-64 pkg_tmp/osx-64
            export PKG_RES="pkg_res"
            conda-build --output-folder pkg_tmp .
            TG=`find pkg_tmp/ -name 'seqkit*bz2'`
            echo $TG
            conda convert -p osx-64 -o $PKG_RES $TG

      - run:
          name: upload seqkit
          command: |
            source $HOME/.bashrc
            conda activate ./conda_base
            export PKG_RES="seqkit/pkg_res"
            PKGS=`find $PKG_RES -name 'seqkit*bz2'`
            for PKG in $PKGS
            do 
            echo $PKG
            anaconda -t ${ANACONDA_TOKEN} upload --force --register -u bsipos -l main $PKG
            done


      - run:
          name: build csvtk (linux)
          command: |
            source $HOME/.bashrc
            conda activate ./conda_base
            PKG_NAME=csvtk
            BASE=`pwd -P`/csvtk
            export PATH=`pwd -P`/conda_base/go/bin:$PATH
            export GOPATH=`pwd -P`/conda_base/go.pkgs
            export GOROOT=`pwd -P`/conda_base/go
            export GOOS="linux" GOARCH="amd64"
            PKG_NAME=seqkit-bsipos
            cd $GOPATH/src/github.com/shenwei356/csvtk/csvtk
            git remote add bsipos https://github.com/bsipos/csvtk.git
            git fetch --all 
            git reset --hard bsipos/master
            COM=`git rev-parse --short HEAD`
            VER=$(grep 'const VERSION' cmd/version.go | sed -r 's/^.*= "(.+)"$/\1/')
            echo $VER
            export BUILD_STRING="${COM}"
            sed "s/const VERSION = .*$/const VERSION = \"${VER}_${BUILD_STRING}\"/" cmd/version.go > version_tmp.go
            mv version_tmp.go cmd/version.go
            go get ./...
            CGO_ENABLED=0 go build -a -tags netgo
            mv csvtk $BASE/
            echo "{% set version = \"$VER\" %}" > $BASE/meta.yaml
            export MY_ARCH="linux_amd64"
            cd $BASE
            cat meta.yaml.in >> meta.yaml
            uname -a
            file csvtk
            conda config --set anaconda_upload no
            export PKG_RES="pkg_res"
            conda-build --output-folder $PKG_RES .


      - run:
          name: build csvtk (MacOS)
          command: |
            source $HOME/.bashrc
            conda activate ./conda_base
            PKG_NAME=csvtk
            BASE=`pwd -P`/csvtk
            export PATH=`pwd -P`/conda_base/go/bin:$PATH
            export GOPATH=`pwd -P`/conda_base/go.pkgs
            export GOROOT=`pwd -P`/conda_base/go
            export GOOS="darwin" GOARCH="amd64"
            PKG_NAME=seqkit-bsipos
            cd $GOPATH/src/github.com/shenwei356/csvtk/csvtk
            #git remote add bsipos https://github.com/bsipos/csvtk.git
            git fetch --all
            git reset --hard bsipos/master
            COM=`git rev-parse --short HEAD`
            VER=$(grep 'const VERSION' cmd/version.go | sed -r 's/^.*= "(.+)"$/\1/')
            echo $VER
            export BUILD_STRING="${COM}"
            sed "s/const VERSION = .*$/const VERSION = \"${VER}_${BUILD_STRING}\"/" cmd/version.go > version_tmp.go
            mv version_tmp.go cmd/version.go
            go get ./...
            CGO_ENABLED=0 go build -a -tags netgo
            mv csvtk $BASE/
            echo "{% set version = \"$VER\" %}" > $BASE/meta.yaml
            export MY_ARCH="osx_amd64"
            cd $BASE
            cat meta.yaml.in >> meta.yaml
            uname -a
            file csvtk
            conda config --set anaconda_upload no
            export PKG_RES="pkg_res"
            conda-build --output-folder pkg_tmp .
            TG=`find pkg_tmp/ -name 'csvtk*bz2'`
            echo $TG
            conda convert -p osx-64 -o $PKG_RES $TG

      - run:
          name: upload csvtk
          command: |
            source $HOME/.bashrc
            conda activate ./conda_base
            export PKG_RES="csvtk/pkg_res"
            PKGS=`find $PKG_RES -name 'csvtk*bz2'`
            echo $PKG
            for PKG in $PKGS;
            do
            echo $PKG
            anaconda -t ${ANACONDA_TOKEN} upload --force --register -u bsipos -l main $PKG
            done


      #- store_artifacts:
      #       path: test-reports
      #       destination: test-reports
